import type { Metadata } from "next";
import "@/app/globals.css";
import { cn } from "./lib/utils";
import { lato, league_gothic } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "APEX | Violences Conjugales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        `${lato.variable}`,
        `${league_gothic.variable}`,
        "font-lato text-grey text-xs leading-5 sm:text-sm md:text-base text-pretty scroll-smooth",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
