import { amatic_sc, roboto } from "@/app/ui/fonts";
import type { Metadata } from "next";
import { cn } from "@/app/lib/utils";
import "./globals.css";

export const metadata: Metadata = {
  title: "APEX | Violences Conjugales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        `${roboto.variable}`,
        `${amatic_sc.variable}`,
        "font-roboto text-gray-800 font-light text-pretty",
      )}
    >
      <body>{children}</body>
    </html>
  );
}
