import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import "./globals.css";

import { Lato, League_Gothic } from "next/font/google";
import { cn } from "../../lib/utils";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

const league_gothic = League_Gothic({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-gothic",
});

export const metadata: Metadata = {
  title: "APEX | Violences Conjugales",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        `${lato.variable}`,
        `${league_gothic.variable}`,
        "font-lato text-grey text-xs leading-5 sm:text-sm md:text-base text-pretty scroll-smooth"
      )}
    >
      <body>{children}</body>
    </html>
  );
}
